name: ioredis
description: Redis driver
version: 1.0.0-beta.0
repository: https://github.com/dartondox/ioredis

environment:
  sdk: ^3.1.0

dependencies:
  async: ^2.5.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
